export const DEPARTMENTS = [
  'human-resources',
  'personnel-department',
  'commercial',
  'purchasing',
  'maintenance',
  'monitoring',
  'operations',
  'cleaning',
  'financial',
  'information-technology',
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const PERMISSION_RESOURCES = [
  'dashboard',
  'users',
  'human-resources',
  'personnel-department',
  'commercial',
  'purchasing',
  'maintenance',
  'monitoring',
  'operations',
  'cleaning',
  'drivers',
  'financial',
  'clients',
  'ai-agents',
  'whatsapp-conversations',
  'manuals',
  'reports',
  'settings',
  'profile',
  'contracts',
  'quotes',
  'trips',
  'documents',
  'invoices',
  'service-requests',
  'support',
] as const;

export const PERMISSION_ACTIONS = [
  'view',
  'create',
  'update',
  'delete',
  'manage',
  'use',
  'approve',
  'export',
] as const;

export type PermissionResource = (typeof PERMISSION_RESOURCES)[number];
export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export const PERMISSION_ACTIONS_BY_RESOURCE = {
  dashboard: ['view'],
  users: ['view', 'create', 'update', 'delete', 'manage'],
  'human-resources': ['view', 'create', 'update', 'delete', 'manage'],
  'personnel-department': ['view', 'create', 'update', 'delete', 'manage'],
  commercial: ['view', 'create', 'update', 'delete', 'manage'],
  purchasing: ['view', 'create', 'update', 'delete', 'manage'],
  maintenance: ['view', 'create', 'update', 'delete', 'manage'],
  monitoring: ['view', 'create', 'update', 'delete', 'manage'],
  operations: ['view', 'create', 'update', 'delete', 'manage'],
  cleaning: ['view', 'create', 'update', 'delete', 'manage'],
  drivers: ['view', 'create', 'update', 'delete', 'manage'],
  financial: [
    'view',
    'create',
    'update',
    'delete',
    'manage',
    'approve',
    'export',
  ],
  clients: ['view', 'create', 'update', 'delete', 'manage'],
  'ai-agents': ['view', 'create', 'update', 'delete', 'manage', 'use'],
  'whatsapp-conversations': ['view', 'manage'],
  manuals: ['view', 'create', 'update', 'delete', 'manage'],
  reports: ['view', 'create', 'update', 'delete', 'manage', 'export'],
  settings: ['view', 'update', 'manage'],
  profile: ['view', 'update'],
  contracts: ['view', 'create', 'update', 'delete', 'manage'],
  quotes: ['view', 'create', 'update', 'delete', 'manage', 'approve'],
  trips: ['view', 'create', 'update', 'delete', 'manage'],
  documents: ['view', 'create', 'update', 'delete', 'manage'],
  invoices: ['view', 'create', 'update', 'delete', 'manage'],
  'service-requests': ['view', 'create', 'update', 'manage'],
  support: ['view', 'create', 'update', 'manage'],
} as const satisfies Record<PermissionResource, readonly PermissionAction[]>;

export type PermissionCode = {
  [
    Resource in PermissionResource
  ]: `${Resource}:${(typeof PERMISSION_ACTIONS_BY_RESOURCE)[Resource][number]}`;
}[PermissionResource];

export const ALL_PERMISSION_CODES: readonly PermissionCode[] =
  PERMISSION_RESOURCES.flatMap((resource) =>
    PERMISSION_ACTIONS_BY_RESOURCE[resource].map(
      (action) => `${resource}:${action}` as PermissionCode,
    ),
  );

const permissionCodeSet = new Set<string>(ALL_PERMISSION_CODES);

export function isPermissionCode(value: string): value is PermissionCode {
  return permissionCodeSet.has(value);
}

export const DEFAULT_DEPARTMENT_PERMISSIONS: Readonly<
  Record<Department, readonly PermissionCode[]>
> = {
  'human-resources': [
    'dashboard:view',
    'human-resources:view',
    'human-resources:create',
    'human-resources:update',
    'human-resources:manage',
    'users:view',
    'manuals:view',
    'ai-agents:use',
    'reports:view',
  ],
  'personnel-department': [
    'dashboard:view',
    'personnel-department:view',
    'personnel-department:create',
    'personnel-department:update',
    'personnel-department:manage',
    'users:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  commercial: [
    'dashboard:view',
    'commercial:view',
    'commercial:create',
    'commercial:update',
    'commercial:manage',
    'clients:view',
    'clients:create',
    'clients:update',
    'whatsapp-conversations:manage',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  purchasing: [
    'dashboard:view',
    'purchasing:view',
    'purchasing:create',
    'purchasing:update',
    'purchasing:manage',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  maintenance: [
    'dashboard:view',
    'maintenance:view',
    'maintenance:create',
    'maintenance:update',
    'maintenance:manage',
    'operations:view',
    'drivers:view',
    'manuals:view',
    'reports:view',
  ],
  monitoring: [
    'dashboard:view',
    'monitoring:view',
    'monitoring:create',
    'monitoring:update',
    'monitoring:manage',
    'operations:view',
    'drivers:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  operations: [
    'dashboard:view',
    'operations:view',
    'operations:create',
    'operations:update',
    'operations:manage',
    'monitoring:view',
    'maintenance:view',
    'cleaning:view',
    'drivers:view',
    'drivers:manage',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  cleaning: [
    'dashboard:view',
    'cleaning:view',
    'cleaning:update',
    'operations:view',
    'manuals:view',
  ],
  financial: [
    'dashboard:view',
    'financial:view',
    'financial:create',
    'financial:update',
    'financial:manage',
    'financial:approve',
    'financial:export',
    'commercial:view',
    'clients:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  'information-technology': [
    'dashboard:view',
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'users:manage',
    'ai-agents:view',
    'ai-agents:create',
    'ai-agents:update',
    'ai-agents:delete',
    'ai-agents:manage',
    'ai-agents:use',
    'manuals:view',
    'manuals:create',
    'manuals:update',
    'manuals:delete',
    'manuals:manage',
    'reports:view',
    'reports:export',
    'settings:view',
    'settings:update',
    'settings:manage',
  ],
};

export const DEFAULT_ROLE_PERMISSIONS: Readonly<
  Record<string, readonly PermissionCode[]>
> = {
  administrator: ALL_PERMISSION_CODES,
  director: [
    'dashboard:view',
    'users:view',
    'users:manage',
    'human-resources:view',
    'human-resources:manage',
    'personnel-department:view',
    'personnel-department:manage',
    'commercial:view',
    'commercial:manage',
    'purchasing:view',
    'purchasing:manage',
    'maintenance:view',
    'maintenance:manage',
    'monitoring:view',
    'monitoring:manage',
    'operations:view',
    'operations:manage',
    'cleaning:view',
    'cleaning:manage',
    'drivers:view',
    'drivers:manage',
    'financial:view',
    'financial:manage',
    'financial:approve',
    'clients:view',
    'clients:manage',
    'whatsapp-conversations:manage',
    'ai-agents:view',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
    'settings:view',
  ],
  manager: [
    'dashboard:view',
    'whatsapp-conversations:manage',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],
  driver: ['dashboard:view', 'drivers:view', 'operations:view', 'manuals:view'],
};
